.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.\" "verbatim" environment (from strace.1)
.de CW
.sp
.nf
.ft CW
..
.de CE
.ft
.fi
.sp
..
.TH  su-to-root 1 "20 October 1998" "Debian Project" "Debian GNU/Linux manual"
.SH NAME
su-to-root \- A simple script to give an `interactive' front end to su.
It can be used in menu entry commands to ask for the root password
.SH SYNOPSIS
.B su-to-root [\-p <user>] \-c <command>
.SH DESCRIPTION
Most menu entries simply start an editor or a game or whatever. But
some menu entries would like to give the user the ability to change
important settings in the system, that require root privileges. 
.B su-to-root
can be used to ask for the root password.

.SH COPYING
.B su-to-root
is distributed under the GNU General Public License.
(GPL 2.0 or greater).
.SH AUTHOR
joost witteveen
.RI <joostje@debian.org>
less
.SH "SEE ALSO"
.BR update-menus (1),
.BR menufile (5),
.BR /usr/share/doc/menu/html
